import time, os, pickle, shutil, datetime, re
#import networkx as x
import rdflib as r
import percolation as P
c=P.utils.check

def publishLog(fname,fpath,aname=None,scriptpath=None,created_at=None,channel_info="channel #labmarambira at Freenode"):
    if nor aname:
        name=aname=fname.split(".")[0]
    if not created_at:
        datetime_snapshot=datetime.datetime.now()
    tg=P.rdf.makeBasicGraph([["po","irc"],[P.rdf.ns.po,P.rdf.ns.irc]],"My facebook ego friendship network")
    tg2=P.rdf.makeBasicGraph([["po","irc"],[P.rdf.ns.po,P.rdf.ns.irc]],"RDF metadata for the facebook friendship network of my son")
    ind=P.rdf.IC([tg2],P.rdf.ns.po.Snapshot,
            aname,"Snapshot {}".format(aname))
    P.rdf.link([tg2],ind,"Snapshot {}".format(aname),
                          [P.rdf.ns.po.createdAt,
                          P.rdf.ns.po.triplifiedIn,
                          P.rdf.ns.po.donatedBy,
                          P.rdf.ns.po.availableAt,
                          P.rdf.ns.po.originalFile,
                          P.rdf.ns.po.rdfFile,
                          P.rdf.ns.po.ttlFile,
                          P.rdf.ns.po.discorveryRDFFile,
                          P.rdf.ns.po.discoveryTTLFile,
                          P.rdf.ns.po.acquiredThrough,
                          P.rdf.ns.rdfs.comment,
                          ],
                          [datetime_snapshot,
                           datetime.datetime.now(),
                           name,
                           "https://github.com/ttm/".format(aname),
                           "https://raw.githubusercontent.com/ttm/{}/master/base/{}".format(aname,fname.split("/")[-1]),
                           "https://raw.githubusercontent.com/ttm/{}/master/rdf/{}Translate.owl".format(aname,aname),
                           "https://raw.githubusercontent.com/ttm/{}/master/rdf/{}Translate.ttl".format(aname,aname),
                                "https://raw.githubusercontent.com/ttm/{}/master/rdf/{}Meta.owl".format(aname,aname),
                                "https://raw.githubusercontent.com/ttm/{}/master/rdf/{}Meta.ttl".format(aname,aname),
                           "Lalenia supybot",
                                "The IRC log of {}".format(channel_info),
                           ])

    with open(fname,"rb") as f:
        t=f.read()
    t=t.decode(errors="ignore")
    # get users, messages, times
    d={}
    exp=r"(\d{4})\-(\d{2})\-(\d{2})T(\d{2}):(\d{2}):(\d{2})  \<(.*)\> (.*)"
    count=0
    for match in re.findall(exp,aa):
        year, month, day, hour, minute, second, nick, msg=match
        # achar direct message
        directed_to=re.findall(r"^[^\s]*:"msg)
        if directed_to:
            nick2=directed_to[0][:-1]
            msg_=re.findall(r"^[^\s]*:\s*(.*)",msg)
        dt=datetime.datetime(year,month,day,hour,minute,second)
        # triplificar

        # cria indivíduos: mensagem e usuarios para os nicks
        ind=P.rdf.IC([tg],P.rdf.ns.irc.Participant,"{}-{}".format(aname,nick))
        uris=[P.rdf.ns.irc.nick]
        data=[nick]
        # usuario se conecta com o nick (strings)
        P.rdf.link([tg],ind,nick,uris,data)
        if directed_to:
            ind2=P.rdf.IC([tg],P.rdf.ns.irc.Participant,"{}-{}".format(aname,nick2))
            data=[nick2]
            P.rdf.link([tg],ind,nick,uris,data)

        # mensagem se conecta com usuarios (URIS) e textos (strings)
        imsg=P.rdf.IC([tg],P.rdf.ns.irc.Message,"{}-{}".format(aname,dt.isoformat()))
        uris=[P.rdf.ns.irc.messageContent]
        data=[msg]
        if directed_to:
            uris+=[P.rdf.ns.irc.cleanedMessage]
            data+=[msg_]
        P.rdf.link_([tg],ind,nick,uris,data)
        if count%1000==0:
            c("check 1000")
    c("tudo em RDF")
    tg_=[tg[0]+tg2[0],tg[1]]
    fpath_="{}/{}/".format(fpath,aname)
    P.rdf.writeAll(tg_,aname+"Translate",fpath_,False,1)
    # copia o script que gera este codigo
    if not os.path.isdir(fpath_+"scripts"):
        os.mkdir(fpath_+"scripts")
    #shutil.copy(this_dir+"/../tests/rdfMyFNetwork2.py",fpath+"scripts/")
    shutil.copy(scriptpath,fpath_+"scripts/")
    # copia do base data
    if not os.path.isdir(fpath_+"base"):
        os.mkdir(fpath_+"base")
    shutil.copy(fname,fpath_+"base/")
    P.rdf.writeAll(tg2,aname+"Meta",fpath_,1)
    # faz um README
    date1=0
    date2=0
    nnicks=0
    ndnicks=0
    ndirect=0
    nmsgs=0
    nops=0
    with open(fpath_+"README","w") as f:
        f.write("""This repo delivers RDF data from the IRC Network {} collected around {}, with messages from {} to {}.
It has {} nicks (~{} different) with {} directed messages.
Total messages count {}
of which {} are operational.
The linked data is available at rdf/ dir and was
generated by the routine in the script/ directory.
Original data from lalenia (a Supybot) in data/\n""".format(
            channel_info,created_at,date1,date2,
            nnicks,ndnicks,ndirect,nmsgs,nops))


    return t
